In [16]:
import numpy as np

# Define the coefficients matrix A
A = np.array([[1/4.7+2, -0.5, -1], 
              [-0.5, 3, -1],
              [1, 1, -2-1/4.7]])

# Define the constants vector b
b = np.array([2.5, 5, 0])

# Solve the system of equations
x = np.linalg.solve(A, b)

# Print the solution
print("Solution:", x)


Solution: [3.10835904 3.12350017 2.81632099]


In [17]:
# Compute the inverse of A
A_inv = np.linalg.inv(A)
X = A_inv @ b
print(X)

[3.10835904 3.12350017 2.81632099]


In [19]:
import numpy as np

# Define the coefficients matrix A
A = np.array([[1.25+1/4.7, -0.5, -0.25], 
              [0.5, -2, 1],
              [0.25, 1, -1.25-1/4.7]])

# Define the constants vector b
b = np.array([2.5, 0, 0])

# Solve the system of equations
x = np.linalg.solve(A, b)

# Print the solution
print("Solution:", x)


Solution: [2.31889984 1.18187022 1.20429052]


In [21]:
A_inv = np.linalg.inv(A)
print(A_inv)

[[ 0.92755994 -0.47274809 -0.48171621]
 [ 0.47274809 -1.00061332 -0.7648526 ]
 [ 0.48171621 -0.7648526  -1.28884709]]
