In [28]:
import numpy as np

# Define the coefficients matrix A
A = np.array([[1/4.7+2, -0.5, -1], 
              [-0.5, 3, -1],
              [1, 1, -2-1/4.7]])

# Define the constants vector b
b = np.array([2.5, 5, 0])

# Solve the system of equations
x = np.linalg.solve(A, b)

# Print the solution
print("Solution:", x)


Solution: [3.10835904 3.12350017 2.81632099]


In [27]:
# Compute the inverse of A
A_inv = np.linalg.inv(A)
b = np.array([[2.5],
             [5],
             [0]])
X = A_inv @ b
print(A_inv)

[[ 0.71163296  0.26585533 -0.44174951]
 [ 0.26585533  0.49177237 -0.34238944]
 [ 0.44174951  0.34238944 -0.80629357]]
